name: NEW TARGET FIRMWARE REQUEST
description: Permintaan Firmware OpenWrt Untuk Target Tertentu
title: "[Firmware Request]: "
labels: enhancement

body:
  - type: textarea
    id: environment
    attributes:
      label: Informasi terkait sistem
      description: Isi informasi yang relevan untuk menentukan masalahnya dengan lebih baik
      placeholder: |
        - Model : Orange Pi Zero 2
        - SOC : Allwinner H616 64bit
        - CPU Arch : Cortex-A53
    validations:
      required: true