---
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: rizkikotet
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
geodata-mode: true
geodata-loader: memconservative
global-client-fingerprint: chrome
keep-alive-interval: 15
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - tcp://1.1.1.1#DNS-SETTING
  - 1.1.1.1#DNS-SETTING
  - https://dns.cloudflare.com/dns-query#DNS-SETTING&h3=true
  - tls://one.one.one.one#DNS-SETTING
  fallback:
  - tcp://1.1.1.1#DNS-SETTING
  - 1.1.1.1#DNS-SETTING
  - https://dns.cloudflare.com/dns-query#DNS-SETTING&h3=true
  - tls://one.one.one.one#DNS-SETTING
  default-nameserver:
  - 112.215.198.248
  - 112.215.198.254
  proxy-server-nameserver:
  - tcp://1.1.1.1#DNS-SETTING
  - 1.1.1.1#DNS-SETTING
  - https://dns.cloudflare.com/dns-query#DNS-SETTING&h3=true
  - tls://one.one.one.one#DNS-SETTING
  - 112.215.198.248
  - 112.215.198.254
  respect-rules: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
tun:
  enable: true
  stack: system
  device: utun
  dns-hijack:
  - tcp://any:53
  gso: true
  gso-max-size: 65536
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
profile:
  store-selected: true
proxy-groups:
- name: DNS-SETTING
  type: select
  disable-udp: false
  proxies:
  - SERVER-BROWSING
  - SERVER-ID
  use:
  - PP-Direct
  url: http://cp.cloudflare.com/generate_204
  interval: 60
- name: SERVER-BROWSING
  type: fallback
  disable-udp: false
  use:
  - PP-Browsing
  url: http://cp.cloudflare.com/generate_204
  interval: 60
- name: SERVER-ID
  type: fallback
  disable-udp: false
  use:
  - PP-Indo
  url: http://cp.cloudflare.com/generate_204
  interval: 60
- name: SERVER-GAME
  type: fallback
  disable-udp: false
  use:
  - PP-Game
  url: http://cp.cloudflare.com/generate_204
  interval: 180
- name: Traffic-Direct
  type: select
  disable-udp: false
  proxies:
  - DIRECT-LB
  - Traffic-Indo
  - Traffic-Browsing
  use:
  - PP-Direct
- name: Traffic-Gaming
  type: select
  disable-udp: false
  proxies:
  - DIRECT-LB
  - SERVER-GAME
  use:
  - PP-Direct
- name: Traffic-Gaming-Port
  type: select
  disable-udp: false
  proxies:
  - DIRECT-LB
  - SERVER-GAME
  use:
  - PP-Direct
- name: Traffic-Browsing
  type: fallback
  disable-udp: false
  proxies:
  - SERVER-BROWSING
  - SERVER-ID
  url: http://cp.cloudflare.com/generate_204
  interval: 180
- name: Traffic-Indo
  type: fallback
  disable-udp: false
  proxies:
  - SERVER-ID
  - SERVER-BROWSING
  url: http://cp.cloudflare.com/generate_204
  interval: 180
- name: Traffic-Manual-Reject
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - Traffic-Browsing
  - Traffic-Indo
- name: Traffic-Porn
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - Traffic-Browsing
  - Traffic-Indo
- name: Traffic-Ads
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - Traffic-Browsing
  - Traffic-Indo
- name: DIRECT-LB
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - PP-Direct
  url: http://cp.cloudflare.com/generate_204
  interval: 180
proxy-providers:
  PP-Indo:
    type: file
    path: "./proxy_provider/pp-indo.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
  PP-Browsing:
    type: file
    path: "./proxy_provider/pp-browsing.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
  PP-Game:
    type: file
    path: "./proxy_provider/pp-gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
  PP-Direct:
    type: file
    path: "./proxy_provider/pp-direct.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
rule-providers:
  RP-Direct:
    type: file
    behavior: classical
    path: "./rule_provider/rp-direct.yaml"
  RP-Umum:
    type: file
    behavior: classical
    path: "./rule_provider/rp-umum.yaml"
  RP-Reject:
    type: file
    behavior: classical
    path: "./rule_provider/rp-reject.yaml"
  RP-Indo:
    type: http
    path: "./rule_provider/rp-indo.yaml"
    url: https://raw.githubusercontent.com/rtaserver/Clash-Rule-IP-Indo/main/rule-indo.yaml
    interval: 600
    proxy: Traffic-Browsing
    behavior: classical
    format: yaml
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,123/136/137-139,Traffic-Direct,udp
- RULE-SET,RP-Direct,Traffic-Direct
- RULE-SET,RP-Reject,Traffic-Manual-Reject
- AND,((NETWORK,udp),(OR,((DST-PORT,443),(GEOSITE,youtube)))),REJECT
- AND,((GEOSITE,oisd-full),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),Traffic-Ads
- AND,((GEOSITE,rule-ads),(NOT,((DOMAIN-SUFFIX,googlesyndication.com)))),Traffic-Ads
- GEOSITE,oisd-nsfw,Traffic-Porn
- GEOIP,GOOGLE,Traffic-Browsing
- GEOSITE,GOOGLE,Traffic-Browsing
- AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),Traffic-Browsing
- AND,((NETWORK,UDP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),Traffic-Browsing
- GEOSITE,rule-gaming,Traffic-Gaming
- AND,((NOT,((RULE-SET,RP-Umum))),(NETWORK,TCP)),Traffic-Gaming-Port
- AND,((NOT,((RULE-SET,RP-Umum))),(NETWORK,UDP)),Traffic-Gaming-Port
- GEOSITE,rule-indo,Traffic-Indo
- GEOSITE,rule-sosmed,Traffic-Indo
- GEOSITE,rule-streaming,Traffic-Indo
- GEOIP,id,Traffic-Indo
- GEOIP,facebook,Traffic-Indo
- GEOIP,netflix,Traffic-Indo
- GEOIP,telegram,Traffic-Indo
- GEOIP,twitter,Traffic-Indo
- RULE-SET,RP-Indo,Traffic-Indo
- GEOSITE,rule-speedtest,Traffic-Browsing
- AND,((RULE-SET,RP-Umum),(NETWORK,TCP)),Traffic-Browsing
- AND,((RULE-SET,RP-Umum),(NETWORK,UDP)),Traffic-Browsing
- MATCH,Traffic-Browsing
