name: Generate OpenWrt Config Matrix (Fast Echo Method)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

env:
  REPO_URL_OPENWRT: https://github.com/openwrt/openwrt
  REPO_URL_LEDE: https://github.com/coolsnowwolf/lede
  REPO_URL_IMMORTALWRT: https://github.com/immortalwrt/immortalwrt
  TZ: Asia/Jakarta
  VERSI_OPENWRT: 'openwrt-24.10'
  VERSI_LEDE: 'master'
  VERSI_IMMORTALWRT: 'openwrt-24.10'

jobs:
  generate_matrix:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        source: ['openwrt', 'lede', 'immortalwrt']
        target: ['x86_64', 'armsr-armv8', 'bcm27xx_bcm2710', 'bcm27xx_bcm2711']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3 python3-pip rsync unzip zlib1g-dev file wget zstd
        sudo timedatectl set-timezone "$TZ"

    - name: Clone OpenWrt source (${{ matrix.source }})
      run: |
        case "${{ matrix.source }}" in
          "openwrt")
            REPO=$REPO_URL_OPENWRT
            BRANCH=$VERSI_OPENWRT
            ;;
          "lede")
            REPO=$REPO_URL_LEDE
            BRANCH=$VERSI_LEDE
            ;;
          "immortalwrt")
            REPO=$REPO_URL_IMMORTALWRT
            BRANCH=$VERSI_IMMORTALWRT
            ;;
        esac
        git clone --depth 1 -b "$BRANCH" "$REPO" openwrt
        echo "CURRENT_VERSI=$BRANCH" >> $GITHUB_ENV

    - name: Generate config from echo target (${{ matrix.target }})
      run: |
        cd openwrt

        echo "::group::Write base target config"
        case "${{ matrix.target }}" in
          "x86_64")
            cat <<EOF > .config
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        EOF
            ;;
          "armsr-armv8")
            cat <<EOF > .config
        CONFIG_TARGET_armsr=y
        CONFIG_TARGET_armsr_armv8=y
        CONFIG_TARGET_armsr_armv8_DEVICE_generic=y
        EOF
            ;;
          "bcm27xx_bcm2710")
            cat <<EOF > .config
        CONFIG_TARGET_bcm27xx=y
        CONFIG_TARGET_bcm27xx_bcm2710=y
        CONFIG_TARGET_bcm27xx_bcm2710_DEVICE_rpi-3=y
        EOF
            ;;
          "bcm27xx_bcm2711")
            cat <<EOF > .config
        CONFIG_TARGET_bcm27xx=y
        CONFIG_TARGET_bcm27xx_bcm2711=y
        CONFIG_TARGET_bcm27xx_bcm2711_DEVICE_rpi-4=y
        EOF
            ;;
        esac
        echo "::endgroup::"

        echo "::group::make defconfig"
        make defconfig
        echo "::endgroup::"

        echo "::group::Save output config"
        CFG_DIR="configs/${{ matrix.source }}/${{ env.CURRENT_VERSI }}"
        mkdir -p "$CFG_DIR"
        cp .config "$CFG_DIR/${{ matrix.target }}.config"
        echo "::endgroup::"

    - name: Upload generated configs
      uses: actions/upload-artifact@v4
      with:
        name: configs-${{ matrix.source }}-${{ matrix.target }}
        path: configs/
        retention-days: 1

  commit_configs:
    needs: generate_matrix
    runs-on: ubuntu-22.04
    if: always()
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        persist-credentials: true

    - name: Download all generated configs
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: configs-*
        merge-multiple: true

    - name: Organize config files
      run: |
        # Remove existing configs directory to avoid conflicts
        rm -rf configs
        
        # Create new configs directory structure
        mkdir -p configs
        
        # Copy all config files from artifacts
        if [ -d "artifacts/configs" ]; then
          cp -r artifacts/configs/* configs/
        fi
        
        # Clean up artifacts
        rm -rf artifacts
        
        # List generated configs for debugging
        echo "Generated config files:"
        find configs -name "*.config" -type f | sort

    - name: Commit and push config changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add all config files
        git add configs/
        
        # Check if there are changes to commit
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update: Generated config for all targets ($(date '+%Y-%m-%d %H:%M:%S'))"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}